"""
Utils Package

Contains utility functions, logging configuration, and helper classes.
"""

from .exceptions import (
    AppException,
    ValidationError,
    ServiceError,
    ExternalServiceError,
    VideoNotFoundError,
    VideoGenerationError,
    RAGError,
    AgentError,
    AWSError,
    ConfigurationError,
    AuthenticationError,
    AuthorizationError,
)

from .logging import (
    JSONFormatter,
    ContextFilter,
    LoggerMixin,
    setup_logging,
    get_logger,
    log_function_call,
    log_performance,
    log_context,
    log_method_calls,
    log_async_method_calls,
    log_api_request,
)

from .logging_config import (
    get_logging_config,
    configure_application_logging,
    get_service_logger_context,
    get_request_logger_context,
)

from .helpers import (
    generate_uuid,
    generate_short_id,
    hash_string,
    get_current_timestamp,
    format_timestamp,
    parse_timestamp,
    safe_json_loads,
    safe_json_dumps,
    sanitize_filename,
    ensure_directory,
    get_file_size,
    format_file_size,
    chunk_list,
    flatten_dict,
    deep_merge_dicts,
    retry,
    async_retry,
    timing,
    async_timing,
    run_in_thread,
    validate_email,
    validate_url,
    truncate_string,
    camel_to_snake,
    snake_to_camel,
    is_valid_uuid,
)

from .validators import (
    ValidationResult,
    Validator,
    RequiredValidator,
    StringValidator,
    NumberValidator,
    EmailValidator,
    URLValidator,
    UUIDValidator,
    DateTimeValidator,
    FileValidator,
    ListValidator,
    DictValidator,
    validate_data,
    validate_and_raise,
)

from .security import (
    hash_password,
    verify_password,
    generate_secure_token,
    generate_api_key,
    create_jwt_token,
    verify_jwt_token,
    create_hmac_signature,
    verify_hmac_signature,
    encrypt_data,
    decrypt_data,
    generate_encryption_key,
    sanitize_input,
    is_safe_path,
    generate_csrf_token,
    constant_time_compare,
    rate_limit_key,
    SecurityHeaders,
)

from .monitoring import (
    PerformanceMetric,
    SystemMetrics,
    MetricsCollector,
    metrics_collector,
    get_system_metrics,
    monitor_performance,
    monitor_async_performance,
    PerformanceMonitor,
    AsyncPerformanceMonitor,
    start_system_monitoring,
    get_performance_summary,
)

__all__ = [
    # Exceptions
    "AppException",
    "ValidationError",
    "ServiceError",
    "ExternalServiceError",
    "VideoNotFoundError",
    "VideoGenerationError",
    "RAGError",
    "AgentError",
    "AWSError",
    "ConfigurationError",
    "AuthenticationError",
    "AuthorizationError",
    # Logging
    "JSONFormatter",
    "ContextFilter",
    "LoggerMixin",
    "setup_logging",
    "get_logger",
    "log_function_call",
    "log_performance",
    "log_context",
    "log_method_calls",
    "log_async_method_calls",
    "log_api_request",
    "get_logging_config",
    "configure_application_logging",
    "get_service_logger_context",
    "get_request_logger_context",
    # Helpers
    "generate_uuid",
    "generate_short_id",
    "hash_string",
    "get_current_timestamp",
    "format_timestamp",
    "parse_timestamp",
    "safe_json_loads",
    "safe_json_dumps",
    "sanitize_filename",
    "ensure_directory",
    "get_file_size",
    "format_file_size",
    "chunk_list",
    "flatten_dict",
    "deep_merge_dicts",
    "retry",
    "async_retry",
    "timing",
    "async_timing",
    "run_in_thread",
    "validate_email",
    "validate_url",
    "truncate_string",
    "camel_to_snake",
    "snake_to_camel",
    "is_valid_uuid",
    # Validators
    "ValidationResult",
    "Validator",
    "RequiredValidator",
    "StringValidator",
    "NumberValidator",
    "EmailValidator",
    "URLValidator",
    "UUIDValidator",
    "DateTimeValidator",
    "FileValidator",
    "ListValidator",
    "DictValidator",
    "validate_data",
    "validate_and_raise",
    # Security
    "hash_password",
    "verify_password",
    "generate_secure_token",
    "generate_api_key",
    "create_jwt_token",
    "verify_jwt_token",
    "create_hmac_signature",
    "verify_hmac_signature",
    "encrypt_data",
    "decrypt_data",
    "generate_encryption_key",
    "sanitize_input",
    "is_safe_path",
    "generate_csrf_token",
    "constant_time_compare",
    "rate_limit_key",
    "SecurityHeaders",
    # Monitoring
    "PerformanceMetric",
    "SystemMetrics",
    "MetricsCollector",
    "metrics_collector",
    "get_system_metrics",
    "monitor_performance",
    "monitor_async_performance",
    "PerformanceMonitor",
    "AsyncPerformanceMonitor",
    "start_system_monitoring",
    "get_performance_summary",
]