# Development Configuration Template
# This template provides a complete configuration for development environment

workflow:
  name: "video-generation-dev"
  version: "1.0.0"
  environment: "development"

models:
  planner_model:
    provider: "openrouter"
    model_name: "anthropic/claude-3.5-sonnet"
    temperature: 0.7
    max_tokens: 4000
    timeout: 60
  
  code_model:
    provider: "openrouter"
    model_name: "anthropic/claude-3.5-sonnet"
    temperature: 0.3
    max_tokens: 8000
    timeout: 120
  
  helper_model:
    provider: "openrouter"
    model_name: "anthropic/claude-3-haiku"
    temperature: 0.7
    max_tokens: 4000
    timeout: 30

rag:
  enabled: true
  vector_store_path: "data/rag/chroma_db"
  embedding_model: "hf:ibm-granite/granite-embedding-30m-english"
  chunk_size: 1000
  chunk_overlap: 200
  similarity_threshold: 0.7
  max_results: 5
  enable_caching: true
  cache_ttl: 1800  # 30 minutes for development

features:
  use_rag: true
  use_visual_analysis: false  # Disabled for faster development
  enable_caching: true
  use_context_learning: true
  use_gpu_acceleration: false
  preview_mode: true  # Faster rendering for development

performance:
  max_retries: 2  # Fewer retries for faster feedback
  timeout_seconds: 180  # Shorter timeout for development
  max_concurrent_scenes: 3  # Lower concurrency for development
  max_concurrent_renders: 2
  circuit_breaker:
    failure_threshold: 3
    timeout: 30
    half_open_max_calls: 2

quality:
  default_quality: "low"  # Faster rendering for development
  resolution:
    width: 1280
    height: 720
  frame_rate: 24

paths:
  output_dir: "output/dev"
  context_learning_path: "data/context_learning"
  manim_docs_path: "data/rag/manim_docs"
  chroma_db_path: "data/rag/chroma_db"

monitoring:
  enabled: true
  use_langfuse: false  # Disabled for development
  print_cost: true
  verbose: true  # Verbose logging for development
  metrics_collection:
    step_durations: true
    success_rates: true
    resource_usage: false  # Disabled for performance
  health_check:
    enabled: true
    interval_seconds: 120

security:
  input_validation:
    max_topic_length: 200
    max_description_length: 2000
    allowed_file_extensions: [".mp4", ".avi", ".mov", ".mkv"]
  api_keys:
    encryption_enabled: false  # Disabled for development
    rotation_interval_days: 365

checkpointing:
  enabled: true
  provider: "memory"  # Use memory for development
  cleanup:
    max_age_hours: 24  # Clean up after 1 day
    max_count: 100

error_handling:
  strategies:
    retry:
      max_attempts: 2
      backoff_factor: 1.5
      max_delay: 30
    fallback_models:
      - "openrouter/anthropic/claude-3-haiku"
      - "openrouter/openai/gpt-4o-mini"
    human_loop:
      enabled: true
      timeout_seconds: 600  # 10 minutes
  escalation:
    max_automatic_retries: 2
    escalate_after_minutes: 5